#!/usr/bin/env bash
# Create a portable bundle (DB dump + wordpress files + manifest) from the running DemoStore containers.
#
# SNAPSHOT_EXCLUDE_WPVIVID_ZIPS (default 1): omit WPvivid backup archives under wp-content/wpvividbackups/
# (*.zip, *.zip.part, *.zip.tmp). Those are redundant with this snapshot and often add 40–50MB+ each.
# Set SNAPSHOT_EXCLUDE_WPVIVID_ZIPS=0 to bundle them anyway.
set -euo pipefail

PORTABLE_DIR="$(cd "$(dirname "$0")" && pwd)"
CONTAINER_WP="${CONTAINER_WP:-demostore_wp}"
CONTAINER_DB="${CONTAINER_DB:-demostore_mysql}"
OUT_DIR="${1:-"$PORTABLE_DIR/bundles/$(date +%Y%m%d-%H%M%S)"}"

require() { command -v "$1" >/dev/null 2>&1 || { echo "Missing command: $1" >&2; exit 1; }; }
require docker

if ! docker ps --format '{{.Names}}' | grep -qx "$CONTAINER_WP"; then
  echo "Container not running: $CONTAINER_WP" >&2
  exit 1
fi
if ! docker ps --format '{{.Names}}' | grep -qx "$CONTAINER_DB"; then
  echo "Container not running: $CONTAINER_DB" >&2
  exit 1
fi

echo "Output: $OUT_DIR"
mkdir -p "$OUT_DIR"

db_pass="$(docker exec "$CONTAINER_WP" sed -n "s/.*'DB_PASSWORD', '\([^']*\)'.*/\1/p" /var/www/html/wp-config.php | head -1)"
if [[ -z "$db_pass" ]]; then
  echo "Could not read DB_PASSWORD from wp-config.php inside $CONTAINER_WP" >&2
  exit 1
fi

db_user="$(docker exec "$CONTAINER_WP" printenv WORDPRESS_DB_USER 2>/dev/null || true)"
[[ -z "$db_user" ]] && db_user="wordpress"

db_name="$(docker exec "$CONTAINER_WP" printenv WORDPRESS_DB_NAME 2>/dev/null || true)"
[[ -z "$db_name" ]] && db_name="demostore"

root_pass="$(docker inspect "$CONTAINER_DB" --format '{{range .Config.Env}}{{println .}}{{end}}' | sed -n 's/^MYSQL_ROOT_PASSWORD=//p' | head -1)"
[[ -z "$root_pass" ]] && root_pass="password"

echo "Dumping database $db_name (via $CONTAINER_DB)..."
docker exec "$CONTAINER_DB" mysqldump \
  -u"$db_user" -p"$db_pass" \
  --single-transaction --quick --routines --triggers --no-tablespaces \
  "$db_name" | gzip -1 > "$OUT_DIR/demostore.sql.gz"

echo "Archiving /var/www/html from $CONTAINER_WP..."
excluded_wpvivid=0
tar_exclude=()
if [[ "${SNAPSHOT_EXCLUDE_WPVIVID_ZIPS:-1}" == "1" ]]; then
  excluded_wpvivid=1
  echo "  (excluding WPvivid backup ZIPs under wp-content/wpvividbackups/ — set SNAPSHOT_EXCLUDE_WPVIVID_ZIPS=0 to include)"
  tar_exclude+=(
    --exclude='wp-content/wpvividbackups/*.zip'
    --exclude='wp-content/wpvividbackups/*.zip.part'
    --exclude='wp-content/wpvividbackups/*.zip.tmp'
  )
fi
docker exec "$CONTAINER_WP" tar czf - "${tar_exclude[@]}" -C /var/www/html . > "$OUT_DIR/wordpress.tar.gz"

siteurl=""
home=""
if docker exec "$CONTAINER_DB" mysql -u"$db_user" -p"$db_pass" "$db_name" -N -e "SELECT 1" >/dev/null 2>&1; then
  siteurl="$(docker exec "$CONTAINER_DB" mysql -u"$db_user" -p"$db_pass" "$db_name" -N -r -e \
    "select option_value from wp_options where option_name='siteurl' limit 1" 2>/dev/null | tr -d '\r' || true)"
  home="$(docker exec "$CONTAINER_DB" mysql -u"$db_user" -p"$db_pass" "$db_name" -N -r -e \
    "select option_value from wp_options where option_name='home' limit 1" 2>/dev/null | tr -d '\r' || true)"
fi

wp_ip="$(docker inspect "$CONTAINER_WP" --format '{{range .Config.Env}}{{println .}}{{end}}' | sed -n 's/^WORDPRESS_IP=//p' | head -1)"
[[ -z "$wp_ip" ]] && wp_ip="0.0.0.0"

host="$(hostname || true)"

manifest="$OUT_DIR/manifest.env"
{
  echo "# Auto-generated by snapshot.sh — contains secrets; treat like production credentials."
  echo "BUNDLE_CREATED=$(date -Iseconds)"
  echo "SOURCE_HOSTNAME=$host"
  echo "MYSQL_DATABASE=$db_name"
  echo "MYSQL_USER=$db_user"
  echo "MYSQL_PASSWORD=$db_pass"
  echo "MYSQL_ROOT_PASSWORD=$root_pass"
  echo "WP_SITEURL=$siteurl"
  echo "WP_HOME=$home"
  echo "WORDPRESS_IP=$wp_ip"
  echo "WP_PUBLISH_PORT=${WP_PUBLISH_PORT:-7171}"
  echo "MYSQL_PUBLISH_PORT=${MYSQL_PUBLISH_PORT:-3308}"
  echo "SNAPSHOT_EXCLUDED_WPVIVID_ZIPS=$excluded_wpvivid"
} >"$manifest"
chmod 600 "$manifest"

cp "$PORTABLE_DIR/docker-compose.yml" "$OUT_DIR/"
cp "$PORTABLE_DIR/restore.sh" "$OUT_DIR/"
cp "$PORTABLE_DIR/env.example" "$OUT_DIR/"

echo ""
echo "Done."
echo "  $(du -sh "$OUT_DIR" | awk '{print $1}')  $OUT_DIR"
echo "On the target VPS: use the restore.sh inside this folder (or copy the latest from demostore-portable/)."
echo "Optional settings: cp env.example restore.local.env  (do not use .env in the bundle directory)"
echo "  cd $OUT_DIR && ./restore.sh"
